---
name: Molecule Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        # TODO Add more versions when moving forward
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
        with:
          path: ansible-role-cjdns
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install docker
          pip install --user pipenv
          # If the upper one does not work
          # curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          ls
          pipenv install
      - name: Test with molecule
        env:
          HCLOUD_TOKEN: ${{secrets.HCLOUD_TOKEN}}
        run: |
          ls -alh
          cd ansible-role-cjdns
          ls -alh
          pipenv run molecule test
